
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
      # MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      # MINIO_ROOT_PASSWORD:  ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "29000:9000"  # MiniIO API
      - "29001:9001"  # MiniIO Console
    restart: unless-stopped
    volumes: 
      - minio_data:/data 
      - minio_config:/root/.minio 

    networks:
      - travel_network
volumes:
  minio_data:
  minio_config:
networks:
  travel_network: {}